### ISSUE TITLE
Going beyond 426 ScreenWidth causes the game to soft lock in Collision Chaos Zone 3

### ISSUE THREAD

**Issue by nayutune** [Rubberduckycooly/Sonic-CD-11-Decompilation#233] opened 2024-01-23 15:05 UTC
### Expected Behavior

Normally character can walk out of the area because the camera doesn't get locked

### Actual Behavior

Camera gets a static lock and the player is prevented from walking back out to take another path

### Steps to Reproduce

1. Set the ScreenWidth to 427 (or above)
2. Go to collision chaos Zone 3
3. Visit top path before you go down to the boss location.

### Screenshots

![cd](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/assets/74027819/335b4bdb-4411-4e74-87d1-6eea33dba264)

### Decompilation Version

RSDKv3 built from source.

### Game Version

Blit Release (Steam/XBOX 360/PS3)

### Game Revision

Latest Steam version.

### Script Platform Type

Standard

### Renderer Type

Software Renderer

### Platform

PC - Windows 10

### Additional Comments

Seems to be another bug related to changing aspect ratio.

It's functional on 426.

But if you if throw in MegAmisAdditions + Sonic CD Miracle Edition: If "Extended Camera" is enabled then that value needs to be just below 404 for it to work properly. (or disabling it otherwise)

**Comment by MegAmi24** [comment] 2024-01-23 15:36
This is not a bug with the engine nor the decomp; this is simply a result of the Flower Pod object (which is responsible for locking the camera here) being active due to the screen width. This game wasn't fully optimized for ultrawide, so issues like this will occur and, as far as this project is concerned, this is intended behavior. Closing.

**Closed by MegAmi24** 2024-01-23 15:36 UTC
Labels: bug
