### ISSUE TITLE
Crash on special stage

### ISSUE THREAD

**Issue by TheGag96** [Rubberduckycooly/Sonic-CD-11-Decompilation#84] opened 2021-02-07 21:14 UTC
Was playing a special stage at the end of Quartz Quadrant. Noticed the background seemed to be using the wrong tiles/texture, which looked very strange when turning, and then the game just segfaulted. 

Playing on Linux x64, built from latest master as of this post, Data.rsdk extracted from the Amazon Appstore Android release when it was free (marked version 1.1.0). (Sorry I don't have any other info to give!)

**Comment by vaguerant** [comment] 2021-02-08 14:30
This is a duplicate of #64 (resolved); the fix will be in future builds.

**Closed** 2021-02-15 00:02 UTC
