### ISSUE TITLE
Game does not respond to Fullscreen property in settings.ini

### ISSUE THREAD

**Issue by Decidetto** [Rubberduckycooly/Sonic-CD-11-Decompilation#26] opened 2021-01-18 13:58 UTC
On Windows platforms (I have tested 8.1 and 10 20H2), setting the `Fullscreen`property to true does not seem to have any effect and in fact resets it to false upon opening the game.

Using the rsdk file from the latest version of the Steam release.

**Comment by parkerlreed** [comment] 2021-01-18 16:25
What platform? Just tested on Linux and Fullscreen borderless is working great.

**Comment by Decidetto** [comment] 2021-01-18 16:32
My mistake! I've added it to the description.

**Comment by parkerlreed** [comment] 2021-01-18 17:16
Yeah it's really easy to compile. Readme mentions the deps, and it's a single `make` away

**Comment by Decidetto** [comment] 2021-01-18 18:55
My Pop_OS desktop wouldn't acknowledge the dependencies even though they were installed, but Arch on my laptop compiled it without a hitch. Can confirm that the Fullscreen settting is acknowledged properly on Linux! (Though it crashed to desktop upon reaching an act results screen and there's no log, hmm...)

**Comment by parkerlreed** [comment] 2021-01-18 19:19
Pop_OS and other Debian based need the `-dev` equivalents installed along with the main package. Arch packages the dev libraries into the main packages, negating the extra packages.

Got through the first level fine here (Also Arch). Results came up and next level started shortly after.

**Comment by jedinjapan** [comment] 2021-01-19 01:01
Windows 10, x64 build experiencing same issue. Fullscreen does not take effect upon startup.

Using F4 to switch to Fullscreen after startup works as intended.

**Comment by Rubberduckycooly** [comment] 2021-01-19 08:55
this is a known and fixed bug, it will be in the next build (which should be later this week)

**Closed by Rubberduckycooly** 2021-01-19 08:55 UTC
