### ISSUE TITLE
Special Stage 5 glitches and crashes with the Android Data.rsdk

### ISSUE THREAD

**Issue by ObiDriftKenobi** [Rubberduckycooly/Sonic-CD-11-Decompilation#64] opened 2021-01-24 19:21 UTC
![image](https://user-images.githubusercontent.com/35656715/105640912-3bae4180-5e81-11eb-9e6a-b3fb1a0108bc.png)

There's not much I can say about it because I just don't know. This happened after Quartz Quadrant Z1, I entered from the past that I made a good future in. I replayed it twice and it always crashed around when I destroyed the second UFO. It's apparently Special Stage 5.

I use the android Data.rsdk.

Is there any debugging tool I could use to get some more info for you? I'd like to help more than just being annoying on github, but I don't understand much about RSDK decompiling.

Thanks and have a nice day.

**Comment by ObiDriftKenobi** [comment] 2021-01-24 19:22
Forgot to mension: I am on latest.

**Comment by MANGOM1LK** [comment] 2021-01-24 21:50
I had a similar effect using the pre-Sega Forever Android 1.0.6 RSDK, with the same discolored controller overlay and glitched background. The objects move way too fast, and when the Time Stone appears, it leaves a trail behind. However, my game never crashes.

I loaded straight into Special Stage 5 from the debug menu, which might be relevant. The issue isn't present with the Steam RSDK.

**Comment by Rubberduckycooly** [comment] 2021-01-24 23:57
we'll look into this bug, as it's been reported by a few people at this point

**Comment by vaguerant** [comment] 2021-01-25 13:42
Another weird Android jerk checking in here. I just wanted to note that I tested several of the free, ad-supported Sega Forever versions to check whether any of them avoided this issue. I was not successful, all versions I tried exhibited the same issue. My tested versions:

- v1.0.0 (first release)
- v1.0.9
- v2.0.0
- v2.0.1 (latest release, published today [!] as of this comment)

I'm not planning on testing versions 1.0.2 to 1.0.6, which are all of the other releases I could easily find online. Since the issue has existed since before *and* after those versions, it seems unlikely that there was a period in between where the issue didn't occur.

**Comment by Piccadili-Hill** [comment] 2021-01-25 15:09
I have the same issue.

To remove : your input HUD on screen go to sprite global --> Dpad 
(use GIMP or paint) 
And recolor all the image in purple

same for special stage

go sprite --> special

and recolor the image in purple (only where there is the images of the input)

**Comment by ObiDriftKenobi** [comment] 2021-01-25 16:35
> I have the same issue.
> 
> To remove : your input HUD on screen go to sprite global --> Dpad
> (use GIMP or paint)
> And recolor all the image in purple
> 
> same for special stage
> 
> go sprite --> special
> 
> and recolor the image in purple (only where there is the images of the input)

Except... the controls aren't the problem. I don't give a single _sonic forces_ about the controls being visible, the whole thing is glitchy.

**Comment by Rubberduckycooly** [comment] 2021-02-03 23:44
fixed, the fix will be in the next build

**Closed by Rubberduckycooly** 2021-02-03 23:44 UTC

**Comment by ObiDriftKenobi** [comment] 2021-02-04 19:44
You're a god.
