### ISSUE TITLE
The menu on the Decompliled mobile apk has the menu glitch even though the width is at 424

### ISSUE THREAD

**Issue by TheBrockReal** [Rubberduckycooly/Sonic-CD-11-Decompilation#241] opened 2024-06-18 12:34 UTC
### Expected Behavior

The glitch to not happen 

### Actual Behavior

The menu looks awful 

### Steps to Reproduce

I don't know any steps to reduce it cause I'm not that smart 

### Screenshots

![Screenshot_20240618_082413_RSDKv3](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/assets/81770173/a1e3133e-c34f-40a0-b7c9-e090c9285283)

### Decompilation Version

The mobile version 

### Game Version

Blit Release (Steam/XBOX 360/PS3)

### Script Platform Type

Mobile

### Renderer Type

Software Renderer

### Platform

Samsung Galaxy S23 Ultra/Android 

### Additional Comments

Just want this to be fixed

**Comment by MegAmi24** [comment] 2024-06-18 12:57
Duplicate of #198. Closing.

**Closed by MegAmi24** 2024-06-18 12:57 UTC
Labels: bug

**Comment by TheBrockReal** [comment] 2024-06-19 10:58
This should not be closed

**Comment by TheBrockReal** [comment] 2024-06-19 11:13
> Duplicate of #198. Closing.

You are nothing but a joke

You say that there is mods to fix it but they isn't 
Unless you use the PC version 

And I'm not going to use the PC version just to get the screen to be correct 

I'm staying with emulating Sonic CD on the Gems Collection on my PS2 emulator

**Comment by LittlePlanetCD** [comment] 2024-06-19 14:12
Just going to leave this here:

This behavior from the Steam RSDK file is normal, as that version of the game was not built for Ultrawide in mind, causing issues like this. This is not an engine bug. (You're not playing on 424 width by the way, the mobile app adjusts width based on your resolution.)

This issue can be fixed via using the [CD Scripts](https://github.com/Rubberduckycooly/Sonic-CD-2011-Script-Decompilation) and turning TxtScripts to true in Settings.ini.

Also, if you're going to play on mobile, it's more suggested to use the Mobile RSDK file, to fix possible other issues.

Don't be hostile in the issues you report, as we won't help you if you are.
